"""empty message

Revision ID: 83ef8d5f608c
Revises: c494c5b060ee
Create Date: 2022-11-28 01:19:43.864088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83ef8d5f608c'
down_revision = 'c494c5b060ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earth_curve', schema=None) as batch_op:
        batch_op.alter_column('curve_data',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earth_curve', schema=None) as batch_op:
        batch_op.alter_column('curve_data',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
