"""empty message

Revision ID: bae27bc1d172
Revises: 
Create Date: 2022-11-28 00:18:53.382479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae27bc1d172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earth_curve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('sampling_rate', sa.String(length=100), nullable=False),
    sa.Column('delta', sa.String(length=100), nullable=False),
    sa.Column('npts', sa.String(length=100), nullable=False),
    sa.Column('calib', sa.String(length=100), nullable=False),
    sa.Column('_format', sa.String(length=100), nullable=False),
    sa.Column('curve_data', sa.Text(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earth_curve')
    # ### end Alembic commands ###
