"""empty message

Revision ID: c494c5b060ee
Revises: bae27bc1d172
Create Date: 2022-11-28 01:02:17.252730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c494c5b060ee'
down_revision = 'bae27bc1d172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earth_curve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curve_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earth_curve', schema=None) as batch_op:
        batch_op.drop_column('curve_id')

    # ### end Alembic commands ###
