"""empty message

Revision ID: c6532012549a
Revises: 512585b9d9eb
Create Date: 2022-11-28 01:59:09.697564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6532012549a'
down_revision = '512585b9d9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earth_curve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('sampling_rate', sa.String(length=100), nullable=False),
    sa.Column('delta', sa.String(length=100), nullable=False),
    sa.Column('npts', sa.String(length=100), nullable=False),
    sa.Column('calib', sa.String(length=100), nullable=False),
    sa.Column('_format', sa.String(length=100), nullable=False),
    sa.Column('curve_id', sa.String(length=100), nullable=False),
    sa.Column('curve_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curve_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earth_curve')
    # ### end Alembic commands ###
