"""empty message

Revision ID: cff3034cc71e
Revises: 
Create Date: 2022-12-21 17:05:17.387917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff3034cc71e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earth_curve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('sampling_rate', sa.String(length=100), nullable=False),
    sa.Column('delta', sa.String(length=100), nullable=False),
    sa.Column('npts', sa.String(length=100), nullable=False),
    sa.Column('calib', sa.String(length=100), nullable=False),
    sa.Column('_format', sa.String(length=100), nullable=False),
    sa.Column('curve_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('magnitude', sa.String(length=100), nullable=True),
    sa.Column('p_start_time', sa.DateTime(), nullable=True),
    sa.Column('intensity', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earth_curve')
    # ### end Alembic commands ###
